In [ ]:
import pandas as pd
import numpy as np

#  **Data** **Loading**

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Sample - Superstore.csv to Sample - Superstore.csv

In [ ]:
df = pd.read_csv("Sample - Superstore.csv", encoding="latin1")

#  **Data** **exploring**

In [ ]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
df.shape

(9994, 21)

In [ ]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [ ]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

#  **missing and duplicated values**

In [ ]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

#  **Data cleaning**

In [ ]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

In [ ]:
df[["Sales", "Quantity", "Discount", "Profit"]].describe()

              Sales     Quantity     Discount       Profit
count   9994.000000  9994.000000  9994.000000  9994.000000
mean     229.858001     3.789574     0.156203    28.656896
std      623.245101     2.225110     0.206452   234.260108
min        0.444000     1.000000     0.000000 -6599.978000
25%       17.280000     2.000000     0.000000     1.728750
50%       54.490000     3.000000     0.200000     8.666500
75%      209.940000     5.000000     0.200000    29.364000
max    22638.480000    14.000000     0.800000  8399.976000

In [39]:
df["Year"] = df["Order Date"].dt.year
df["Month"] = df["Order Date"].dt.month
df["Month Name"] = df["Order Date"].dt.month_name()
df["Quarter"] = df["Order Date"].dt.quarter

In [ ]:
df["Shipping Day Delay"] = (df["Ship Date"] - df["Order Date"]).dt.days

In [40]:
def get_profitability_status(profit):
    if profit > 0:
        return "Profitable"
    elif profit < 0:
        return "Loss"

In [ ]:
def get_discount_level(discount):
    if discount == 0:
        return "No Discount"
    elif discount < 0.30:
        return "Low Discount"
    elif discount >= 0.30:
        return "High Discount"

#  **Business questions**

What is the total sales generated by the business?

In [ ]:
total_sales = df["Sales"].sum()
print("Total Sales",total_sales)

Total Sales 2297200.8603000003

How many orders were placed by customers?

In [ ]:
total_orders = df["Order ID"].nunique()
print("Total orders",total_orders)

Total orders 5009

What is the overall profit margin of the business?

In [ ]:
total_profit = df["Profit"].sum()
total_sales = df["Sales"].sum()
profit_margin = (total_profit / total_sales) * 100
print("profit margin",profit_margin)

profit margin 12.467217240315604

How many products were sold in total?

In [ ]:
total_quantity = df["Quantity"].sum()
print("total quantity",total_quantity)

total quantity 37873

How do sales and profit vary across different product sub categories?

In [ ]:
subcategory_analysis = df.groupby("Sub-Category").agg(
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum")
).reset_index()

How does profit vary across different shipment modes?

In [ ]:
shipping_analysis = df.groupby("Ship Mode").agg(
    Profit=("Profit", "sum")
).reset_index()

Which top 5 specific products generate the most overall revenue?

In [41]:
t5 = df.groupby("Product Name").agg(
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum"),
    Quantity=("Quantity", "sum")
).reset_index()
t5_top5 = t5.sort_values("Sales",ascending=False).head(5)
print(t5_top5)

                                          Product Name      Sales  \
404              Canon imageCLASS 2200 Advanced Copier  61599.824
650  Fellowes PB500 Electric Punch Plastic Comb Bin...  27453.384
444  Cisco TelePresence System EX90 Videoconferenci...  22638.480
786       HON 5400 Series Task Chairs for Big and Tall  21870.576
686         GBC DocuBind TL300 Electric Binding System  19823.479

           Profit  Quantity
404  2.519993e+04        20
650  7.753039e+03        31
444 -1.811078e+03         6
786  5.684342e-14        39
686  2.233505e+03        37

Which months or quarters of the year consistently bring in the highest sales spike?

In [42]:
month_q = df.groupby(["Year", "Month", "Month Name"]).agg(
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum")
).reset_index()
month_q = month_q.sort_values(["Year", "Month"])
print(month_q)

    Year  Month Month Name        Sales      Profit
0   2014      1    January   14236.8950   2450.1907
1   2014      2   February    4519.8920    862.3084
2   2014      3      March   55691.0090    498.7299
3   2014      4      April   28295.3450   3488.8352
4   2014      5        May   23648.2870   2738.7096
5   2014      6       June   34595.1276   4976.5244
6   2014      7       July   33946.3930   -841.4826
7   2014      8     August   27909.4685   5318.1050
8   2014      9  September   81777.3508   8328.0994
9   2014     10    October   31453.3930   3448.2573
10  2014     11   November   78628.7167   9292.1269
11  2014     12   December   69545.6205   8983.5699
12  2015      1    January   18174.0756  -3281.0070
13  2015      2   February   11951.4110   2813.8508
14  2015      3      March   38726.2520   9732.0978
15  2015      4      April   34195.2085   4187.4962
16  2015      5        May   30131.6865   4667.8690
17  2015      6       June   24797.2920   3335.5572
18  2015      7       July   28765.3250   3288.6483
19  2015      8     August   36898.3322   5355.8084
20  2015      9  September   64595.9180   8209.1627
21  2015     10    October   31404.9235   2817.3660
22  2015     11   November   75972.5635  12474.7884
23  2015     12   December   74919.5212   8016.9659
24  2016      1    January   18542.4910   2824.8233
25  2016      2   February   22978.8150   5004.5795
26  2016      3      March   51715.8750   3611.9680
27  2016      4      April   38750.0390   2977.8149
28  2016      5        May   56987.7280   8662.1464
29  2016      6       June   40344.5340   4750.3781
30  2016      7       July   39261.9630   4432.8779
31  2016      8     August   31115.3743   2062.0693
32  2016      9  September   73410.0249   9328.6576
33  2016     10    October   59687.7450  16243.1425
34  2016     11   November   79411.9658   4011.4075
35  2016     12   December   96999.0430  17885.3093
36  2017      1    January   43971.3740   7140.4391
37  2017      2   February   20301.1334   1613.8720
38  2017      3      March   58872.3528  14751.8915
39  2017      4      April   36521.5361    933.2900
40  2017      5        May   44261.1102   6342.5828
41  2017      6       June   52981.7257   8223.3357
42  2017      7       July   45264.4160   6952.6212
43  2017      8     August   63120.8880   9040.9557
44  2017      9  September   87866.6520  10991.5556
45  2017     10    October   77776.9232   9275.2755
46  2017     11   November  118447.8250   9690.1037
47  2017     12   December   83829.3188   8483.3468

Which regions or states are making the least profit?

In [45]:
region_q = df.groupby("Region").agg(
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum")).reset_index()
region_q = region_q.sort_values("Profit")
print(region_q)

state_q = df.groupby("State").agg(
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum")
).reset_index()
state_q = state_q.sort_values("Profit")
print("\n",state_q.head(10))

    Region        Sales       Profit
0  Central  501239.8908   39706.3625
2    South  391721.9050   46749.4303
1     East  678781.2400   91522.7800
3     West  725457.8245  108418.4489

              State        Sales      Profit
41           Texas  170188.0458 -25729.3563
33            Ohio   78258.1360 -16971.3766
36    Pennsylvania  116511.9140 -15559.9603
11        Illinois   80166.1010 -12607.8870
31  North Carolina   55603.1640  -7490.9122
4         Colorado   32108.1180  -6527.8579
40       Tennessee   30661.8730  -5341.6936
1          Arizona   35282.0010  -3427.9246
8          Florida   89473.7080  -3399.3017
35          Oregon   17431.1500  -1190.4705

Which customer group spends the most per order?

In [46]:
q7_orders = df.groupby(
    ["Segment", "Order ID"]).agg(Order_Sales=("Sales", "sum")).reset_index()
q7 = q7_orders.groupby("Segment").agg(
    Total_Sales=("Order_Sales", "sum"),Number_of_Orders=("Order ID", "nunique"),
    Average_Order_Value=("Order_Sales", "mean")
).reset_index()

print(q7)

       Segment   Total_Sales  Number_of_Orders  Average_Order_Value
0     Consumer  1.161401e+06              2586           449.111116
1    Corporate  7.061464e+05              1514           466.411075
2  Home Office  4.296531e+05               909           472.665730

Do bigger discounts actually bring in more sales volume?

In [47]:
dis8 = df.groupby("Discount Level").agg(
    Sales=("Sales", "sum"),
    Quantity=("Quantity", "sum"),
    Orders=("Order ID", "nunique"),
    Profit=("Profit", "sum")).reset_index()

print(dis8)

  Discount Level         Sales  Quantity  Orders       Profit
0           High  1.032267e+05       849     211  -10369.2774
1            Low  5.436935e+04       373      89    9029.1770
2         Medium  7.921529e+05     13858    2436   91756.2975
3    No Discount  1.087908e+06     18267    2644  320987.6032
4      Very High  2.595435e+05      4526     888 -125006.7786

Which categories and subcategories generate the most sales and profit?

In [48]:
q1_category = df.groupby("Category").agg(
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum"),
    Quantity=("Quantity", "sum")).reset_index()

print(q1_category)

          Category        Sales       Profit  Quantity
0        Furniture  741999.7953   18451.2728      8028
1  Office Supplies  719047.0320  122490.8008     22906
2       Technology  836154.0330  145454.9481      6939

In [49]:
q1_subcategory = df.groupby("Sub-Category").agg(Sales=("Sales", "sum"),Profit=("Profit", "sum"),Quantity=("Quantity", "sum")).reset_index()
q1_subcategory = q1_subcategory.sort_values("Sales",ascending=False)
print(q1_subcategory)

   Sub-Category        Sales      Profit  Quantity
13       Phones  330007.0540  44515.7306      3289
5        Chairs  328449.1030  26590.1663      2356
14      Storage  223843.6080  21278.8264      3158
16       Tables  206965.5320 -17725.4811      1241
3       Binders  203412.7330  30221.7633      5974
11     Machines  189238.6310   3384.7569       440
0   Accessories  167380.3180  41936.6357      2976
6       Copiers  149528.0300  55617.8249       234
4     Bookcases  114879.9963  -3472.5560       868
1    Appliances  107532.1610  18138.0054      1729
9   Furnishings   91705.1640  13059.1436      3563
12        Paper   78479.2060  34053.5693      5178
15     Supplies   46673.5380  -1189.0995       647
2           Art   27118.7920   6527.7870      3000
7     Envelopes   16476.4020   6964.1767       906
10       Labels   12486.3120   5546.2540      1400
8     Fasteners    3024.2800    949.5182       914

________________________________________________________________________________

#  **Saving Cleaned CSV**

In [50]:
df.to_csv("superstore_cleaned.csv",index=False)
print("superstore_cleaned.csv created successfully.")

superstore_cleaned.csv created successfully.

In [51]:
from google.colab import files
files.download("superstore_cleaned.csv")