In [1]:
import pandas as pd

#  **Data** **Loading**

In [10]:
df = pd.read_csv("Sample - Superstore.csv", encoding="latin1")

#  **Data** **exploring**

In [11]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [ ]:
df.shape

(9994, 21)

In [ ]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [ ]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

#  **missing and duplicated values**

In [ ]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

#  **Data cleaning**

In [12]:
df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

In [13]:
df[["Sales", "Quantity", "Discount", "Profit"]].describe()

              Sales     Quantity     Discount       Profit
count   9994.000000  9994.000000  9994.000000  9994.000000
mean     229.858001     3.789574     0.156203    28.656896
std      623.245101     2.225110     0.206452   234.260108
min        0.444000     1.000000     0.000000 -6599.978000
25%       17.280000     2.000000     0.000000     1.728750
50%       54.490000     3.000000     0.200000     8.666500
75%      209.940000     5.000000     0.200000    29.364000
max    22638.480000    14.000000     0.800000  8399.976000

In [14]:
df["Year"] = df["Order Date"].dt.year
df["Month"] = df["Order Date"].dt.month
df["Month Name"] = df["Order Date"].dt.month_name()
df["Quarter"] = df["Order Date"].dt.quarter

In [15]:
df["Shipping Day Delay"] = (df["Ship Date"] - df["Order Date"]).dt.days

In [16]:
def get_profitability_status(profit):
    if profit > 0:
        return "Profitable"
    elif profit < 0:
        return "Loss"

In [ ]:
# Create the Profitability Status column
df['Profitability Status'] = df['Profit'].apply(get_profitability_status)

In [18]:
def get_discount_level(discount):
    if discount == 0:
        return "No Discount"
    elif discount < 0.30:
        return "Low Discount"
    elif discount >= 0.30:
        return "High Discount"

In [19]:
# Create the Discount Level column
df['Discount Level'] = df['Discount'].apply(get_discount_level)

In [20]:
# Preview the new columns
df[['Profit', 'Profitability Status', 'Discount', 'Discount Level']].head()

     Profit Profitability Status  Discount Discount Level
0   41.9136           Profitable      0.00    No Discount
1  219.5820           Profitable      0.00    No Discount
2    6.8714           Profitable      0.00    No Discount
3 -383.0310                 Loss      0.45  High Discount
4    2.5164           Profitable      0.20   Low Discount

#  **Business questions**

What is the total sales generated by the business?

In [23]:
total_sales = df["Sales"].sum()
print("Total Sales:",total_sales)

Total Sales: 2297200.8603

How many orders were placed by customers?

In [24]:
total_orders = df["Order ID"].count()
print("Total orders:",total_orders)

Total orders: 9994

What is the overall profit margin of the business?

In [25]:
total_profit = df["Profit"].sum()
total_sales = df["Sales"].sum()
profit_margin = (total_profit / total_sales) * 100
print("profit margin:",profit_margin)

profit margin: 12.467217240315605

How many products were sold in total?

In [26]:
total_quantity = df["Quantity"].sum()
print("Total quantity:",total_quantity)

Total quantity: 37873

How do sales and profit vary across different product sub categories?

In [31]:
subcategory_analysis = df.groupby("Sub-Category").agg(
    Sales=("Sales", sum),
    Profit=("Profit", sum)
)
subcategory_analysis

                    Sales      Profit
Sub-Category
Accessories   167380.3180  41936.6357
Appliances    107532.1610  18138.0054
Art            27118.7920   6527.7870
Binders       203412.7330  30221.7633
Bookcases     114879.9963  -3472.5560
Chairs        328449.1030  26590.1663
Copiers       149528.0300  55617.8249
Envelopes      16476.4020   6964.1767
Fasteners       3024.2800    949.5182
Furnishings    91705.1640  13059.1436
Labels         12486.3120   5546.2540
Machines      189238.6310   3384.7569
Paper          78479.2060  34053.5693
Phones        330007.0540  44515.7306
Storage       223843.6080  21278.8264
Supplies       46673.5380  -1189.0995
Tables        206965.5320 -17725.4811

How does profit vary across different shipment modes?

In [32]:
shipping_analysis = df.groupby("Ship Mode").agg(
    Profit=("Profit", "sum")
)
shipping_analysis

                     Profit
Ship Mode
First Class      48969.8399
Same Day         15891.7589
Second Class     57446.6354
Standard Class  164088.7875

Which top 5 specific products generate the most overall revenue?

In [33]:
t5 = df.groupby("Product Name").agg(
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum"),
    Quantity=("Quantity", "sum")
)
t5

t5_top5 = t5.sort_values("Sales",ascending=False).head(5)
print(t5_top5)

                                                        Sales        Profit  \
Product Name
Canon imageCLASS 2200 Advanced Copier               61599.824  2.519993e+04
Fellowes PB500 Electric Punch Plastic Comb Bind...  27453.384  7.753039e+03
Cisco TelePresence System EX90 Videoconferencin...  22638.480 -1.811078e+03
HON 5400 Series Task Chairs for Big and Tall        21870.576  5.684342e-14
GBC DocuBind TL300 Electric Binding System          19823.479  2.233505e+03

                                                    Quantity
Product Name
Canon imageCLASS 2200 Advanced Copier                     20
Fellowes PB500 Electric Punch Plastic Comb Bind...        31
Cisco TelePresence System EX90 Videoconferencin...         6
HON 5400 Series Task Chairs for Big and Tall              39
GBC DocuBind TL300 Electric Binding System                37

Which months or quarters of the year consistently bring in the highest sales spike?

In [34]:
month_q = df.groupby(["Year", "Month", "Month Name"]).agg(
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum")
).sort_values(["Year", "Month"])
print(month_q)

                             Sales      Profit
Year Month Month Name
2014 1     January      14236.8950   2450.1907
     2     February      4519.8920    862.3084
     3     March        55691.0090    498.7299
     4     April        28295.3450   3488.8352
     5     May          23648.2870   2738.7096
     6     June         34595.1276   4976.5244
     7     July         33946.3930   -841.4826
     8     August       27909.4685   5318.1050
     9     September    81777.3508   8328.0994
     10    October      31453.3930   3448.2573
     11    November     78628.7167   9292.1269
     12    December     69545.6205   8983.5699
2015 1     January      18174.0756  -3281.0070
     2     February     11951.4110   2813.8508
     3     March        38726.2520   9732.0978
     4     April        34195.2085   4187.4962
     5     May          30131.6865   4667.8690
     6     June         24797.2920   3335.5572
     7     July         28765.3250   3288.6483
     8     August       36898.3322   5355.8084
     9     September    64595.9180   8209.1627
     10    October      31404.9235   2817.3660
     11    November     75972.5635  12474.7884
     12    December     74919.5212   8016.9659
2016 1     January      18542.4910   2824.8233
     2     February     22978.8150   5004.5795
     3     March        51715.8750   3611.9680
     4     April        38750.0390   2977.8149
     5     May          56987.7280   8662.1464
     6     June         40344.5340   4750.3781
     7     July         39261.9630   4432.8779
     8     August       31115.3743   2062.0693
     9     September    73410.0249   9328.6576
     10    October      59687.7450  16243.1425
     11    November     79411.9658   4011.4075
     12    December     96999.0430  17885.3093
2017 1     January      43971.3740   7140.4391
     2     February     20301.1334   1613.8720
     3     March        58872.3528  14751.8915
     4     April        36521.5361    933.2900
     5     May          44261.1102   6342.5828
     6     June         52981.7257   8223.3357
     7     July         45264.4160   6952.6212
     8     August       63120.8880   9040.9557
     9     September    87866.6520  10991.5556
     10    October      77776.9232   9275.2755
     11    November    118447.8250   9690.1037
     12    December     83829.3188   8483.3468

Which regions or states are making the least profit?

In [35]:
region_q = df.groupby("Region").agg(
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum")).sort_values("Profit")
print(region_q)

state_q = df.groupby("State").agg(
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum")
).sort_values("Profit")
print("\n",state_q.head(10))

               Sales       Profit
Region
Central  501239.8908   39706.3625
South    391721.9050   46749.4303
East     678781.2400   91522.7800
West     725457.8245  108418.4489

                       Sales      Profit
State
Texas           170188.0458 -25729.3563
Ohio             78258.1360 -16971.3766
Pennsylvania    116511.9140 -15559.9603
Illinois         80166.1010 -12607.8870
North Carolina   55603.1640  -7490.9122
Colorado         32108.1180  -6527.8579
Tennessee        30661.8730  -5341.6936
Arizona          35282.0010  -3427.9246
Florida          89473.7080  -3399.3017
Oregon           17431.1500  -1190.4705

Which customer group spends the most per order?

In [37]:
q7_orders = df.groupby(
    ["Segment", "Order ID"]).agg(
        Order_Sales=("Sales", "sum")
        ).reset_index()
q7 = q7_orders.groupby("Segment").agg(
    Total_Sales=("Order_Sales", "sum"),Number_of_Orders=("Order ID", "nunique"),
    Average_Order_Value=("Order_Sales", "mean")
)

print(q7)

              Total_Sales  Number_of_Orders  Average_Order_Value
Segment
Consumer     1.161401e+06              2586           449.111116
Corporate    7.061464e+05              1514           466.411075
Home Office  4.296531e+05               909           472.665730

Do bigger discounts actually bring in more sales volume?

In [38]:
dis8 = df.groupby("Discount Level").agg(
    Sales=("Sales", "sum"),
    Quantity=("Quantity", "sum"),
    Orders=("Order ID", "nunique"),
    Profit=("Profit", "sum"))

print(dis8)

                       Sales  Quantity  Orders       Profit
Discount Level
High Discount   3.627701e+05      5375    1020 -135376.0560
Low Discount    8.465222e+05     14231    2507  100785.4745
No Discount     1.087908e+06     18267    2644  320987.6032

Which categories and subcategories generate the most sales and profit?

In [39]:
q1_category = df.groupby("Category").agg(
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum"),
    Quantity=("Quantity", "sum"))

print(q1_category)

                       Sales       Profit  Quantity
Category
Furniture        741999.7953   18451.2728      8028
Office Supplies  719047.0320  122490.8008     22906
Technology       836154.0330  145454.9481      6939

In [40]:
q1_subcategory = df.groupby("Sub-Category").agg(
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum"),
    Quantity=("Quantity", "sum")).sort_values("Sales",ascending=False)

print(q1_subcategory)

                    Sales      Profit  Quantity
Sub-Category
Phones        330007.0540  44515.7306      3289
Chairs        328449.1030  26590.1663      2356
Storage       223843.6080  21278.8264      3158
Tables        206965.5320 -17725.4811      1241
Binders       203412.7330  30221.7633      5974
Machines      189238.6310   3384.7569       440
Accessories   167380.3180  41936.6357      2976
Copiers       149528.0300  55617.8249       234
Bookcases     114879.9963  -3472.5560       868
Appliances    107532.1610  18138.0054      1729
Furnishings    91705.1640  13059.1436      3563
Paper          78479.2060  34053.5693      5178
Supplies       46673.5380  -1189.0995       647
Art            27118.7920   6527.7870      3000
Envelopes      16476.4020   6964.1767       906
Labels         12486.3120   5546.2540      1400
Fasteners       3024.2800    949.5182       914

________________________________________________________________________________

#  **Saving Cleaned CSV**

In [41]:
df.to_csv("superstore_cleaned.csv",index=False)
print("superstore_cleaned.csv created successfully.")

superstore_cleaned.csv created successfully.